# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_card'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=120, null=True)),
                ('nickname', models.CharField(blank=True, help_text='Internal Reference Nickname', max_length=120, null=True)),
                ('delivery_frequency', models.CharField(choices=[('every-week', 'Every Week'), ('every-other-week', 'Every Other Week')], max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
