# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-24 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_deliveryfrequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfrequency',
            name='billing_profile',
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_frequency',
            field=models.CharField(choices=[('every-week', 'Every Week'), ('every-other-week', 'Every Other Week')], default='Every Week', max_length=120),
        ),
        migrations.DeleteModel(
            name='DeliveryFrequency',
        ),
    ]
