# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20200216_0906'),
        ('addresses', '0005_auto_20200225_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.DeliveryZipCode'),
        ),
    ]
