# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-15 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzipcode',
            options={'ordering': ['-delivery_day']},
        ),
        migrations.RenameField(
            model_name='deliveryzipcode',
            old_name='title',
            new_name='delivery_day',
        ),
    ]
