# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_zipcodeimport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryzipcode',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='deliveryzipcode',
            name='zipcodes',
            field=models.ManyToManyField(blank=True, to='delivery.ZipCode'),
        ),
    ]
