# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-16 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20200216_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzipcode',
            options={'ordering': ['delivery_day']},
        ),
    ]
