# Generated by Django 2.1.5 on 2020-07-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['product__slug']},
        ),
    ]
